=== hamza-moustansir/xml_php/input.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ests">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="user">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="username"/>
              <xs:element type="xs:string" name="email"/>
              <xs:element type="xs:string" name="password"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="admin">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="username"/>
              <xs:element type="xs:string" name="email"/>
              <xs:element type="xs:string" name="password"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="candidate" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:byte" name="id"/>
              <xs:element type="xs:string" name="prenom"/>
              <xs:element type="xs:string" name="midlle"/>
              <xs:element type="xs:string" name="nom"/>
              <xs:element type="xs:string" name="sex"/>
              <xs:element type="xs:date" name="date"/>
              <xs:element type="xs:string" name="cni"/>
              <xs:element type="xs:string" name="cne"/>
              <xs:element type="xs:string" name="adresse"/>
              <xs:element type="xs:string" name="ville"/>
              <xs:element type="xs:short" name="postale"/>
              <xs:element type="xs:int" name="mobile"/>
              <xs:element type="xs:string" name="email"/>
              <xs:element type="xs:int" name="apoge"/>
              <xs:element type="xs:float" name="moyen_bac"/>
              <xs:element type="xs:short" name="annee_bac"/>
              <xs:element type="xs:string" name="type_diplome"/>
              <xs:element type="xs:string" name="specialite_diplome"/>
              <xs:element type="xs:byte" name="moyenne_diplome"/>
              <xs:element type="xs:byte" name="classement"/>
              <xs:element type="xs:byte" name="totale"/>
              <xs:element type="xs:byte" name="moyennee_diplome"/>
              <xs:element type="xs:byte" name="classemente"/>
              <xs:element type="xs:byte" name="totalee"/>
              <xs:element type="xs:string" name="choix_1"/>
              <xs:element type="xs:string" name="choix_2"/>
              <xs:element type="xs:string" name="choix_3"/>
              <xs:element type="xs:string" name="status"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== hamza-moustansir/xml_php/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="trans.xsl"?>
<ests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="input.xsd">


    <user>
        <username>hamza</username>
        <email>hamza@gmail.com</email>
        <password>hamza</password>
    </user>
    <admin>
        <username>deko</username>
        <email>deko@gmail.com</email>
        <password>deko</password>
    </admin>
  <user>
        <username>h</username>
        <email>haza@gmail.com</email>
        <password>hamza</password>
    </user>

    <candidate>
        <id>1</id>
        <prenom>Izuku</prenom>
        <midlle>deko</midlle>
        <nom>Midoriya</nom>
        <sex>male</sex>
        <date>
        1003-01-01</date>
        <cni>I455896</cni>
        <cne>K1234563</cne>
        <adresse>Fes centre</adresse>
        <ville>
        Fes</ville>
        <postale>20123</postale>
        <mobile>0625458695</mobile>
        <email>deko@gmail.com</email>
        <apoge>
        20003654</apoge>
        <moyen_bac>19.00</moyen_bac>
        <annee_bac>2020</annee_bac>
        <type_diplome>DEUG</type_diplome>
        <specialite_diplome>
        GI</specialite_diplome>
        <moyenne_diplome>19</moyenne_diplome>
        <classement>1</classement>
        <totale>
        123</totale>
        <moyennee_diplome>18</moyennee_diplome>
        <classemente>1</classemente>
        <totalee>85</totalee>
        <choix_1>
        MÉCATRONIQUE</choix_1>
        <choix_2>MÉTROLOGIE, QUALITÉ, SÉCURITÉ ET ENVIRONNEMENT</choix_2>
        <choix_3>GESTION
        COMPTABLE ET FINANCIÈRE</choix_3>
        <status>en cours</status>
    </candidate>
    <candidate>
        <id>1</id>
        <prenom>Izuku</prenom>
        <midlle>deko</midlle>
        <nom>Midoriya</nom>
        <sex>female</sex>
        <date>
        2003-01-01</date>
        <cni>I455896</cni>
        <cne>K1234563</cne>
        <adresse>Fes centre</adresse>
        <ville>
        Fes</ville>
        <postale>20123</postale>
        <mobile>0625458695</mobile>
        <email>deko@gmail.com</email>
        <apoge>
        20003654</apoge>
        <moyen_bac>19.00</moyen_bac>
        <annee_bac>2019</annee_bac>
        <type_diplome>DEUG</type_diplome>
        <specialite_diplome>
        GI</specialite_diplome>
        <moyenne_diplome>19</moyenne_diplome>
        <classement>1</classement>
        <totale>
        123</totale>
        <moyennee_diplome>18</moyennee_diplome>
        <classemente>1</classemente>
        <totalee>85</totalee>
        <choix_1>
        MÉCATRONIQUE</choix_1>
        <choix_2>MÉTROLOGIE, QUALITÉ, SÉCURITÉ ET ENVIRONNEMENT</choix_2>
        <choix_3>GESTION
        COMPTABLE ET FINANCIÈRE</choix_3>
        <status>en cours</status>
    </candidate>
</ests>
